[package]
name = "carbonbond"
version = "0.1.0"
authors = ["金剛 <yc1043@gmail.com>", "石墨 <why8ther@gmail.com>"]
edition = "2018"
default-run = "server"

[dependencies]
chitin = { git = "https://github.com/carbon-bond/chitin" }
tokio = { version = "0.2", features = ["full"] }
hyper-staticfile = "0.5.3"
hyper = "0.13.6"
log = "0.4.8"
env_logger = "0.6.2"
serde_json = "1.0.40"
serde = { version = "1.0.98", features = ["derive"] }
regex = "1.2.1"
clap = {version = "2.33.0", features = ["yaml"]}
toml = "0.5.1"
state = { version = "0.4.1", features = ["const_fn", "tls"] }
derive_more = "0.15.0"
chrono = { version = "0.4.7", features = ["serde"] }
typescript-definitions = { git = "https://github.com/carbon-bond/typescript-definitions" }
async-trait = "0.1.31"
rustyline = "5.0.2"
redis = "0.16.0"
cookie = { version = "0.14.1", features= ["secure", "percent-encode"] }
time = "0.2.16"

[build-dependencies]
chitin = { git = "https://github.com/carbon-bond/chitin" }
chrono = { version = "0.4.7", features = ["serde"] }
serde = { version = "1.0.98", features = ["derive"] }
typescript-definitions = { git = "https://github.com/carbon-bond/typescript-definitions" }

[[bin]]
name = "server"
path = "src/main.rs"

# [[bin]]
# name = "db-tool"
# path = "src/db_tool.rs"

[lib]
doctest = false
