[package]
name = "carbonbond"
version = "0.1.0"
authors = ["金剛 <yc1043@gmail.com>", "石墨 <why8ther@gmail.com>"]
edition = "2018"
default-run = "server"

[dependencies]
chitin = { git = "https://github.com/carbon-bond/chitin" }
diesel = { version = "1.4.2", features = ["postgres", "r2d2", "chrono"] }
actix-web = "1.0.5"
log = "0.4.8"
env_logger = "0.6.2"
rand = "0.7.0"
rust-argon2 = "0.5.0"
juniper = "0.13.1"
serde_json = "1.0.40"
serde = { version = "1.0.98", features = ["derive"] }
actix = "0.8.3"
actix-session = "0.2.0"
actix-files = "0.1.4"
regex = "1.2.1"
clap = {version = "2.33.0", features = ["yaml"]}
toml = "0.5.1"
state = { version = "0.4.1", features = ["const_fn", "tls"] }
derive_more = "0.15.0"
r2d2 = "0.8.5"
chrono = { version = "0.4.7", features = ["serde"] }
bytes = "0.4.12"
prost = "0.5.0"
actix-web-actors = "1.0.2"
rustyline = "5.0.2"
base64 = "0.10.1"
typescript-definitions = { git = "https://github.com/carbon-bond/typescript-definitions" }

[build-dependencies]
chrono = { version = "0.4.7", features = ["serde"] }
chitin = { git = "https://github.com/carbon-bond/chitin" }
serde = { version = "1.0.98", features = ["derive"] }
prost-build = { version = "0.5.0" }
typescript-definitions = { git = "https://github.com/carbon-bond/typescript-definitions" }

[[bin]]
name = "server"
path = "src/main.rs"

[[bin]]
name = "db-tool"
path = "src/db_tool.rs"

[lib]
doctest = false